app:
  host: 0.0.0.0
  port: 8000
network:
  interface: WiFi
ml:
  # Model paths are now hardcoded in src/models/predict.py
  # Active models located in: trained_models/retrained/
  # - Random Forest: random_forest_calibrated.pkl (60% weight)
  # - Deep Learning: dl_model_retrained_fp_optimized.keras (40% weight)
  # - Scaler: scaler_standard_retrained.pkl
  # - Class Mapping: class_mapping.json
  # Note: These paths are NOT configurable via this file
logging:
  level: INFO
  file: logs/app.log
security:
  high_severity_threshold: 0.8
  block_suspicious: true
detection:
  mode: threshold
  confidence_threshold: 0.3  # Lowered from 0.7 for better detection
  anomaly_multiplier: 2.0
  min_packet_threshold: 5  # Lowered from 10 for better detection
  filter_localhost: true  # Filter out localhost traffic
  filter_private_networks: false  # Keep disabled for broader detection
  localhost_confidence_threshold: 0.8  # Reasonable threshold for local traffic
  require_anomaly_for_localhost: false
  whitelist_ports:
  - 80
  - 443
  - 53
  - 22
  - 25
  - 110
  - 143
  - 993
  - 995
  - 8000
  - 8080
  - 8443
  - 3000
  - 5000
  - 5173  # Vite dev server
  - 3001  # React dev server
  legitimate_port_packet_threshold: 20  # Lowered from 50 for better detection
  # Whitelist trusted IPs (your router and local network)
  whitelist_ips:
  - 192.168.1.1      # Your router/gateway
  - 192.168.1.0/24   # Your entire local subnet
  - 127.0.0.1        # Localhost
  - 169.254.0.0/16   # Link-local addresses
  adaptive_baseline:
    enabled: false
    learning_period: 3600
notifications:
  email:
    enabled: false
    smtp_server: smtp.gmail.com
    smtp_port: 587
    sender_email: your-email@gmail.com
    password: ''
    recipients:
    - security-team@example.com
    - admin@example.com
  sms:
    enabled: false
    account_sid: ''
    auth_token: ''
    from_number: '+263783609981'
    recipients:
    - '+263783609981'
response_actions:
  enabled: false
  auto_block_high_severity: false
  auto_block_medium_severity: false
  rate_limit_threshold: 100
  temp_block_duration: 3600
database:
  enabled: true
  type: sqlite
  directory: data/flows
  retention_days: 30
  save_benign_flows: true
  save_attack_flows: true
  min_confidence_to_save: 0.0
