version: '3.8'

services:
  ids-system:
    build: .
    container_name: unified-ids-system
    ports:
      - "8000:8000"
    cap_add:
      - NET_RAW
      - NET_ADMIN
    environment:
      - PYTHONUNBUFFERED=1
      - TF_CPP_MIN_LOG_LEVEL=3
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped
    networks:
      - ids-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/alerts', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ids-network:
    driver: bridge
